name = "Light Sam. Derived from https://github.com/vickylai/hugo-theme-sam/"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://www.gnu.org/licenses/agpl-3.0.en.html"
description = "Simple And Minimalist theme for Hugo."
homepage = "https://github.com/zeddee/light-sam"
tags = []
features = []
min_version = "0.30"

[author]
  name = "Zed"
  homepage = "https://shootbird.work"
